name: Generate Documentation

on:
  push:
    branches:
      - main  # Runs on updates to the main branch
  pull_request:
    branches:
      - main  # Runs for pull requests targeting the main branch

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai==0.28.0

      # Step 4: Run the documentation generation script
      - name: Generate documentation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/generate_docs_script.py

       # Step 5: Ensure the files exists
      - name: List files in the working directory
        run: ls -R

      # Step 6: Commit and push changes
      - name: Commit and push documentation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update documentation [skip ci]" || echo "No changes to commit"
          git push
